# Generated by Django 4.1.7 on 2023-03-22 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchedmovie',
            name='watched_by',
            field=models.ManyToManyField(related_name='watched_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
