# Generated by Django 4.1.7 on 2023-04-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('note', models.IntegerField(max_length=500)),
                ('poster_path', models.CharField(max_length=100)),
            ],
        ),
    ]
