# Generated by Django 4.1.7 on 2023-04-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmovie',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listmovie',
            name='release_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
