# Generated by Django 4.1.7 on 2023-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
