# Generated by Django 4.1.7 on 2023-04-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listmovie_name_listmovie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmovie',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
