# Generated by Django 4.2 on 2023-04-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_rename_name_listmovie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmovie',
            name='note',
        ),
    ]
