# Generated by Django 4.2 on 2023-04-14 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='update_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
