# Generated by Django 4.1.7 on 2023-03-22 11:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=1000)),
                ('tagline', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('poster_path', models.CharField(max_length=100)),
                ('cover_path', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('liked_by', models.ManyToManyField(related_name='get_liked_movies', to=settings.AUTH_USER_MODEL)),
                ('watched_by', models.ManyToManyField(related_name='get_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
