# Generated by Django 4.1.7 on 2023-04-08 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('original_title', models.CharField(default='', max_length=100)),
                ('poster_path', models.CharField(max_length=100)),
                ('watch_listed', models.ManyToManyField(related_name='watchlist_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('original_title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_movies_set', to=settings.AUTH_USER_MODEL)),
                ('watched_by', models.ManyToManyField(related_name='movies_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.watchedmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='films.watchedmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
