# Generated by Django 4.1.7 on 2023-04-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarylog',
            old_name='movies',
            new_name='movie',
        ),
    ]
