# Generated by Django 4.1.7 on 2023-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_diarylog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='release_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
