# Generated by Django 4.1.7 on 2023-03-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_stars_rating_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='star',
            new_name='stars',
        ),
    ]
