# Generated by Django 4.1.7 on 2023-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_watchedmovie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarylog',
            name='first_film_of_the_month',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
