# Generated by Django 4.1.7 on 2023-04-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_diarylog_first_film_of_the_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarylog',
            name='first_film_of_the_month',
        ),
    ]
