# Generated by Django 4.2 on 2023-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_diarylog_first_film_of_the_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('original_title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
