# Generated by Django 4.2 on 2023-04-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
