# Generated by Django 4.2 on 2023-04-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_watchedmovie_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedmovie',
            old_name='tmdb_id',
            new_name='movie',
        ),
    ]
