# Generated by Django 4.2 on 2023-04-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_rename_tmdb_id_watchedmovie_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedmovie',
            old_name='movie',
            new_name='film',
        ),
    ]
