# Generated by Django 4.1.7 on 2023-04-04 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0011_remove_watchedmovie_cover_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedmovie',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_movies_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
