# Generated by Django 4.1.7 on 2023-04-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_watchedmovie_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
