# Generated by Django 4.2 on 2023-04-15 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0013_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_movies_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='watched_by',
            field=models.ManyToManyField(related_name='movies_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='watchlisted_by',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diarylog',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='films.film'),
        ),
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
