# Generated by Django 4.1.7 on 2023-04-06 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0013_delete_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
