# Generated by Django 4.1.7 on 2023-04-10 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top4Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('poster_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='top4',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='top4',
            name='four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_four', to='profiles.top4movies'),
        ),
        migrations.AlterField(
            model_name='top4',
            name='one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_one', to='profiles.top4movies'),
        ),
        migrations.AlterField(
            model_name='top4',
            name='three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_three', to='profiles.top4movies'),
        ),
        migrations.AlterField(
            model_name='top4',
            name='two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_two', to='profiles.top4movies'),
        ),
    ]
