# Generated by Django 4.1.7 on 2023-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follower_set', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Userfollowing',
        ),
    ]
