# Generated by Django 4.1.7 on 2023-03-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('profiles', '0002_alter_top4_four_alter_top4_one_alter_top4_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top4',
            name='four',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_four', to='films.watchedmovie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='top4',
            name='one',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_one', to='films.watchedmovie'),
        ),
        migrations.AlterField(
            model_name='top4',
            name='three',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_three', to='films.watchedmovie'),
        ),
        migrations.AlterField(
            model_name='top4',
            name='two',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_two', to='films.watchedmovie'),
        ),
    ]
